{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "active_users_ratio{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "active users"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(auth_successes_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(auth_failures_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "request_latency_ms_all_milliseconds_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza creation latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pizza_latency_ms_milliseconds_total{source=\"jwt-pizza-service-dev\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(http_requests_total{endpoint=\"DELETE\"}[1m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(http_requests_total{endpoint=\"GET\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(http_requests_total{endpoint=\"POST\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(http_requests_total{endpoint=\"PUT\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(http_requests_all_total[1m])",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_successes_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_failures_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "Purchase failures"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_revenue_total{source=\"jwt-pizza-service-dev\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}